// The member-paid twin of a template. Same email at the same point in the
// process, but the connected member is signing/paying instead of the client —
// so To/Cc flip (member becomes To, client is auto-Cc'd).
const MV = ' (member signing/paying on clients behalf)'
export const mv = (name, label, recip) => [name + MV, label + ' — version used when the member is paying on the client’s behalf', recip]

// template_name -> [plain-English label, who receives it], listed in the order
// each email fires in the process. "Auto-Cc" = recipients the system always
// adds (client family / assigned PF) — the editable CC/BCC lists below each
// email are the internal-team additions on top of these.
export const TEMPLATE_META = {
  'LOGIN_SETUP': [
    ['MANUAL_login_setup', 'Manually send someone a portal login set-up link (works for members, specialists and clients)', 'To: Chosen recipient'],
    ['password_reset', 'Password Reset (self-service)', 'To: The account holder who requested the reset (member / specialist / tax planner / client)'],
  ],
  'MAP 1': [
    ['PIP_meeting_confirm', 'PIP 1 meeting is booked — confirmation to the client', 'To: Client · Auto-Cc: Member + PF'],
    ['PIP_meeting_declined', 'Client declined the PIP 1 meeting — polite close-out', 'To: Client · Auto-Cc: Member + PF'],
    ['PCADMIN_followup|Undecided', 'After the follow-up meeting the client is undecided — email with the Yes / No decision buttons', 'To: Client · Auto-Cc: Member + PF'],
    mv('PCADMIN_followup|Undecided', 'After the follow-up meeting the client is undecided — email with the Yes / No decision buttons', 'To: Member · Auto-Cc: Client + PF'),
    ['PCADMIN_followup|No', 'Client said no after the follow-up meeting — close-out', 'To: Client · Auto-Cc: Member + PF'],
    mv('PCADMIN_followup|No', 'Client said no after the follow-up meeting — close-out', 'To: Member · Auto-Cc: Client + PF'),
    ['PIP1_reconfirmation|No', 'Client clicked "No" on the decision email — close-out confirmation', 'To: Client · Auto-Cc: Member + PF'],
    ['CONTRACT_agreementsent|Yes', 'Client said yes — congratulations email with the agreement signing link', 'To: Client · Auto-Cc: Member + PF'],
    mv('CONTRACT_agreementsent|Yes', 'Client said yes — congratulations email with the agreement signing link', 'To: Member · Auto-Cc: Client + PF'),
    ['CONTRACT_ceocountersign|Yes', 'Internal — asks Anton (CEO) to countersign once the client has signed', 'To: Anton (CEO)'],
    ['CONTRACT_paymentemail|Yes', 'Agreement fully signed — link to make the first payment', 'To: Client'],
    mv('CONTRACT_paymentemail|Yes', 'Agreement fully signed — link to make the first payment', 'To: Member · Auto-Cc: Client'),
    ['CONTRACT_confirmationemail|card', 'First payment by card — confirmation, no longer sent automatically (card gets the invoice/receipt instead)', 'To: Client · Auto-Cc: Member + PF'],
    mv('CONTRACT_confirmationemail|card', 'First payment by card — confirmation, no longer sent automatically (card gets the invoice/receipt instead)', 'To: Member · Auto-Cc: Client + PF'),
    ['CONTRACT_confirmationemail|ach', 'First payment started by bank transfer (ACH) — confirmation while it clears', 'To: Client · Auto-Cc: Member + PF'],
    mv('CONTRACT_confirmationemail|ach', 'First payment started by bank transfer (ACH) — confirmation while it clears', 'To: Member · Auto-Cc: Client + PF'),
    ['CONTRACT_confirmationemail|check', 'First payment received by check — confirmation', 'To: Client · Auto-Cc: Member + PF'],
    mv('CONTRACT_confirmationemail|check', 'First payment received by check — confirmation', 'To: Member · Auto-Cc: Client + PF'),
    ['CONTRACT_tracy_newcase', 'Internal — tells Tracy a new VFO Services case has paid', 'To: Tracy'],
    ['CONTRACT_invoicereceipt_email|first', 'First payment cleared — invoice and receipt PDFs attached', 'To: Client · Auto-Cc: Member + PF + Tracy'],
    mv('CONTRACT_invoicereceipt_email|first', 'First payment cleared — invoice and receipt PDFs attached', 'To: Member · Auto-Cc: Client + PF + Tracy'),
    ['CONTRACT_invoicereceipt_email|subsequent', 'A later quarterly payment cleared — receipt PDF attached', 'To: Client · Auto-Cc: Member + PF + Tracy'],
    ['CONTRACT_member_revshare|first', 'Revenue share confirmation to the member — first payment received from their client'],
    ['CONTRACT_member_revshare|subsequent', 'Revenue share confirmation to the member — a later quarterly payment received'],
    ['CONTRACT_invoicereceipt_email|failed', 'A scheduled payment failed — asks the client to sort out payment (action required)', 'To: Client'],
    ['CONTRACT_installment_charge_failed', 'A quarterly auto-charge failed — asks the client to pay via the secure payment link'],
    ['CONTRACT_paidbycheck|check', 'Client is paying by check — mailing instructions', 'To: Client'],
    ['CONTRACT_checkreminder|check', 'A check payment is due within 7 business days — reminder', 'To: Client'],
    ['CONTRACT_pcadmin_undecided_reminder', '2-business-day reminder — the client still hasn’t answered the decision email', 'To: Client'],
    mv('CONTRACT_pcadmin_undecided_reminder', '2-business-day reminder — the client still hasn’t answered the decision email', 'To: Member · Auto-Cc: Client'),
    ['CONTRACT_signing_reminder', '2-business-day reminder — the agreement is still unsigned', 'To: Client'],
    mv('CONTRACT_signing_reminder', '2-business-day reminder — the agreement is still unsigned', 'To: Member · Auto-Cc: Client'),
    ['CONTRACT_payment_reminder', '2-business-day reminder — the payment link hasn’t been used yet', 'To: Client'],
    mv('CONTRACT_payment_reminder', '2-business-day reminder — the payment link hasn’t been used yet', 'To: Member · Auto-Cc: Client'),
  ],
  'TAX': [
    ['TAX_request_returns', 'Request Tax Returns step (Tax Planning) — asks the client to upload their tax returns via a secure link', 'To: Client · Cc: PF + Member'],
    ['TAX_request_returns|holistic', 'Request Tax Returns step (Holistic) — Holistic wording of the email asking the client to upload their tax returns via a secure link', 'To: Client · Cc: PF + Member'],
    ['TAX_request_additional_info', 'Request Additional Information step (Tax 1 - Diagnostic, Holistic + Tax Planning) — emails the client the additional information you request with a secure upload link', 'To: Client · Cc: PF + Member + Tax Planner'],
    ['TAX_highlevelmeeting_confirm|Yes', 'High Level Tax Planning meeting is booked — confirmation', 'To: Client · Auto-Cc: Member + PF'],
    ['TAX_presentation_link', 'Sends the member the tax presentation link ahead of the ROI meeting', 'To: Member · Auto-Cc: PF'],
    ['TAX_readyfortax3|Yes', 'Tax assessment result — ready to move ahead with tax planning', 'To: Client · Auto-Cc: Member + PF'],
    ['TAX_readyfortax3|No', 'Tax assessment result — not proceeding right now', 'To: Client · Auto-Cc: Member + PF'],
    ['TAX_decision_undecided', 'Client is undecided after the tax meeting — decision email with Yes / No buttons and the agreement PDF', 'To: Client · Auto-Cc: Member + PF'],
    mv('TAX_decision_undecided', 'Client is undecided after the tax meeting — decision email with Yes / No buttons and the agreement PDF', 'To: Member · Auto-Cc: Client + PF'),
    ['TAX_decision_decline', 'Client declined tax planning — close-out', 'To: Client · Auto-Cc: Member + PF'],
    mv('TAX_decision_decline', 'Client declined tax planning — close-out', 'To: Member · Auto-Cc: Client + PF'),
    ['TAX_decision_reminder', '2-business-day reminder — the tax decision email hasn’t been answered', 'To: Client'],
    mv('TAX_decision_reminder', '2-business-day reminder — the tax decision email hasn’t been answered', 'To: Member · Auto-Cc: Client'),
    ['TAX_tax3_assess_reminder_early', 'Assess form still missing 5 business days before the booked ROI meeting — the EARLIER of the two reminders drafted by the nightly sweep', 'To: Allocated Tax Planner + Team Member · Cc: PF'],
    ['TAX_tax3_assess_reminder_early|vault', 'Vault variant of the 5-business-day early reminder — asks the planner to upload the Tax Assessment PDF into the Sensitive Documents vault section', 'To: Allocated Tax Planner + Team Member · Cc: PF'],
    ['TAX_tax3_assess_reminder', 'Assess form still missing 2 business days before the booked ROI meeting — the LATER, last-call reminder drafted by the nightly sweep', 'To: Allocated Tax Planner + Team Member · Cc: PF'],
    ['TAX_tax3_assess_reminder|vault', 'Vault variant for Innovation Consulting Group — asks the planner to upload the Tax Assessment PDF into the Sensitive Documents vault section', 'To: Allocated Tax Planner + Team Member · Cc: PF'],
    ['TAX_agreementsent|Yes', 'Client said yes — tax agreement signing link', 'To: Client · Auto-Cc: Member + PF'],
    mv('TAX_agreementsent|Yes', 'Client said yes — tax agreement signing link', 'To: Member · Auto-Cc: Client + PF'),
    ['TAX_signing_reminder', '2-business-day reminder — the tax agreement is still unsigned', 'To: Client'],
    mv('TAX_signing_reminder', '2-business-day reminder — the tax agreement is still unsigned', 'To: Member · Auto-Cc: Client'),
    ['TAX_ceocountersign|Yes', 'Internal — asks Anton (CEO) to countersign once the client has signed', 'To: Anton (CEO)'],
    ['TAX_paymentemail|Yes', 'Agreement fully signed — link to pay the tax planning retainer', 'To: Client'],
    mv('TAX_paymentemail|Yes', 'Agreement fully signed — link to pay the tax planning retainer', 'To: Member · Auto-Cc: Client'),
    ['TAX_payment_reminder', '2-business-day reminder — the retainer hasn’t been paid yet', 'To: Client'],
    mv('TAX_payment_reminder', '2-business-day reminder — the retainer hasn’t been paid yet', 'To: Member · Auto-Cc: Client'),
    ['TAX_paidbycheck|check', 'Retainer is being paid by check — mailing instructions', 'To: Client'],
    mv('TAX_paidbycheck|check', 'Retainer is being paid by check — mailing instructions', 'To: Member · Auto-Cc: Client'),
    ['TAX_confirmationemail|card', 'Retainer by card — confirmation, no longer sent automatically (card gets the invoice/receipt instead)', 'To: Client · Auto-Cc: Member'],
    mv('TAX_confirmationemail|card', 'Retainer by card — confirmation, no longer sent automatically (card gets the invoice/receipt instead)', 'To: Member · Auto-Cc: Client'),
    ['TAX_confirmationemail|ach', 'Retainer started by bank transfer (ACH) — confirmation while it clears', 'To: Client · Auto-Cc: Member'],
    mv('TAX_confirmationemail|ach', 'Retainer started by bank transfer (ACH) — confirmation while it clears', 'To: Member · Auto-Cc: Client'),
    ['TAX_confirmationemail|check', 'Retainer received by check — payment confirmation', 'To: Client · Auto-Cc: Member'],
    mv('TAX_confirmationemail|check', 'Retainer received by check — payment confirmation', 'To: Member · Auto-Cc: Client'),
    ['TAX_invoicereceipt_email|retainer', 'Retainer cleared — invoice and receipt PDFs attached', 'To: Client · Auto-Cc: Member + PF + Tracy'],
    mv('TAX_invoicereceipt_email|retainer', 'Retainer cleared — invoice and receipt PDFs attached', 'To: Member · Auto-Cc: Client + PF + Tracy'),
    ['TAX_member_revshare|retainer', 'Revenue share confirmation to the member — tax retainer received from their client'],
    ['TAX_planner_revshare|retainer', 'Tax planner revenue share confirmation — retainer half (sent when the retainer revenue share is transferred)', 'To: Tax Planner · Bcc: Accounting'],
    ['TAX_postreview|Continue', 'After the plan review — continuing; green "Continue now" and red "Refund" buttons (the client must click Continue now — nothing locks in on its own)', 'To: Client · Auto-Cc: Member'],
    mv('TAX_postreview|Continue', 'After the plan review — continuing; green "Continue now" and red "Refund" buttons (the client must click Continue now — nothing locks in on its own)', 'To: Member · Auto-Cc: Client'),
    ['TAX_postreview|Continue|3pay', 'After the plan review, 3-payment plans — continuing; the green "Continue now" click also collects the final retainer', 'To: Client · Auto-Cc: Member'],
    mv('TAX_postreview|Continue|3pay', 'After the plan review, 3-payment plans — continuing; the green "Continue now" click also collects the final retainer', 'To: Member · Auto-Cc: Client'),
    ['TAX_postreview|Undecided', 'After the plan review — undecided; Proceed / Refund buttons', 'To: Client · Auto-Cc: Member'],
    mv('TAX_postreview|Undecided', 'After the plan review — undecided; Proceed / Refund buttons', 'To: Member · Auto-Cc: Client'),
    ['TAX_postreview|Undecided|3pay', 'After the plan review, 3-payment plans — undecided; the green "Proceed" click also collects the final retainer', 'To: Client · Auto-Cc: Member'],
    mv('TAX_postreview|Undecided|3pay', 'After the plan review, 3-payment plans — undecided; the green "Proceed" click also collects the final retainer', 'To: Member · Auto-Cc: Client'),
    ['TAX_postreview|Reminder', '2-business-day reminder — the plan-review decision hasn’t been answered', 'To: Client'],
    mv('TAX_postreview|Reminder', '2-business-day reminder — the plan-review decision hasn’t been answered', 'To: Member · Auto-Cc: Client'),
    ['TAX_postreview_confirmed', 'Client clicked the green Client decision 1 button — confirmation that the engagement continues', 'To: Client · Auto-Cc: Member'],
    mv('TAX_postreview_confirmed', 'Client clicked the green Client decision 1 button — confirmation that the engagement continues', 'To: Member · Auto-Cc: Client'),
    ['TAX_postreview_confirmed|3pay', 'Client clicked the green Client decision 1 button — confirms the engagement and that the final retainer is being collected', 'To: Client · Auto-Cc: Member'],
    mv('TAX_postreview_confirmed|3pay', 'Client clicked the green Client decision 1 button — confirms the engagement and that the final retainer is being collected', 'To: Member · Auto-Cc: Client'),
    ['TAX_final_retainer_charge_failed', 'The final retainer charge failed (common after an ACH initial retainer) — fresh payment link'],
    ['TAX_invoicereceipt_email|final_retainer', 'Final retainer receipt PDF attached (plus a re-issued invoice when the fee was amended at Tax 4)', 'To: Client · Auto-Cc: Member + PF'],
    mv('TAX_invoicereceipt_email|final_retainer', 'Final retainer receipt PDF attached (plus a re-issued invoice when the fee was amended at Tax 4)', 'To: Member · Auto-Cc: Client + PF'),
    ['TAX_refund_email|Yes', 'Retainer refunded — confirmation', 'To: Client · Auto-Cc: Member'],
    mv('TAX_refund_email|Yes', 'Retainer refunded — confirmation', 'To: Member · Auto-Cc: Client'),
    ['TAX_implementdecision|Proceed', 'Implementation going ahead — green "Proceed now" and red "Decline implementation" buttons (nothing is charged until the client clicks Proceed now)', 'To: Client · Auto-Cc: Member'],
    mv('TAX_implementdecision|Proceed', 'Implementation going ahead — green "Proceed now" and red "Decline implementation" buttons (nothing is charged until the client clicks Proceed now)', 'To: Member · Auto-Cc: Client'),
    ['TAX_implementdecision|Undecided', 'Implementation decision needed — Proceed / Decline buttons', 'To: Client · Auto-Cc: Member'],
    mv('TAX_implementdecision|Undecided', 'Implementation decision needed — Proceed / Decline buttons', 'To: Member · Auto-Cc: Client'),
    ['TAX_implementdecision|Proceeding', 'Client clicked Proceed on the implementation decision email — acknowledgment that the implementation fee will now be processed', 'To: Client · Auto-Cc: Member'],
    ['TAX_implementdecision|Not Implementing', 'Client is not implementing the plan — close-out', 'To: Client · Auto-Cc: Member'],
    mv('TAX_implementdecision|Not Implementing', 'Client is not implementing the plan — close-out', 'To: Member · Auto-Cc: Client'),
    ['TAX_implementdecision|Reminder', '2-business-day reminder — the implementation decision hasn’t been answered; sent on both the Proceed and Undecided branches, carrying that branch’s own buttons', 'To: Client'],
    mv('TAX_implementdecision|Reminder', '2-business-day reminder — the implementation decision hasn’t been answered; sent on both the Proceed and Undecided branches, carrying that branch’s own buttons', 'To: Member · Auto-Cc: Client'),
    ['TAX_implementation_charge_failed', 'The implementation charge failed (common after an ACH retainer) — fresh payment link'],
    ['TAX_confirmationemail|implementation', 'Implementation fee charged — payment confirmation', 'To: Client · Auto-Cc: Member'],
    mv('TAX_confirmationemail|implementation', 'Implementation fee charged — payment confirmation', 'To: Member · Auto-Cc: Client'),
    ['TAX_invoicereceipt_email|implementation', 'Implementation fee receipt PDF attached', 'To: Client · Auto-Cc: Member + PF'],
    mv('TAX_invoicereceipt_email|implementation', 'Implementation fee receipt PDF attached', 'To: Member · Auto-Cc: Client + PF'),
    ['TAX_member_revshare|implementation', 'Revenue share confirmation to the member — implementation fee received from their client'],
    ['TAX_planner_revshare|implementation', 'Tax planner revenue share confirmation — implementation half (sent when the implementation revenue share is transferred)', 'To: Tax Planner · Bcc: Accounting'],
    ['TAX_deposit_refund', 'Refund chosen on the Tax Plan Green/Red Light step — deposit refunded in full with decline reason(s) (standalone Tax Planning only)'],
  ],
  'PIP': [
    ['PIP_meeting_confirmation', 'PIP meeting is booked — confirmation', 'To: Client · Auto-Cc: Member + PF'],
    ['PIP_payment', 'Link to pay for the PIP purchase', 'To: Client'],
    ['PIP_confirmation', 'PIP payment started by bank transfer (ACH) — confirmation while it clears (not sent for card, which gets the invoice/receipt)', 'To: Client'],
    ['PIP_invoicereceipt_email', 'PIP payment cleared — invoice and receipt PDFs attached', 'To: Client · Auto-Cc: Member + PF'],
    ['PIP_member_revshare', 'Revenue share confirmation to the member after a PIP purchase'],
  ],
  'REGULAR': [
    ['REGULAR_map4confirm', 'MAP 4 meeting is booked — confirmation, naming the priority’s specialist', 'To: Client · Auto-Cc: Member + PF + Tracy + Tray'],
    ['REGULAR_map4declined', 'Client declined the MAP 4 meeting — close-out', 'To: Client · Auto-Cc: Member + PF + Tracy + Tray'],
    ['REGULAR_map4followup', 'Sent 2 days after the MAP 4 meeting — link to fill in the MAP 4 form', 'To: Client · Auto-Cc: Member + PF + Tracy + Tray'],
    ['REGULAR_map4reminder', 'Reminder — MAP 4 form still not submitted 2 days after the follow-up', 'To: Client · Auto-Cc: Member + PF + Tracy + Tray'],
  ],
  'ADVISOR_ONBOARDING': [
    ['ADVISOR_undecided', 'Advisor is undecided after the intro meeting — decision email with Yes / No buttons', 'To: Advisor'],
    ['ADVISOR_decline', 'Advisor is not proceeding — close-out (also sent on the 14-day auto-decline)', 'To: Advisor'],
    ['ADVISOR_undecided_reminder', '2-business-day reminder — the decision email hasn’t been answered', 'To: Advisor'],
    ['ADVISOR_agreement_sent', 'Advisor said yes — onboarding agreement signing link', 'To: Advisor'],
    ['ADVISOR_signing_reminder', '2-business-day reminder — the agreement is still unsigned', 'To: Advisor'],
    ['ADVISOR_ceo_countersign', 'Internal — asks Anton (CEO) to countersign once the advisor has signed', 'To: Anton (CEO)'],
    ['ADVISOR_payment_link', 'Agreement fully signed — onboarding payment link', 'To: Advisor'],
    ['ADVISOR_payment_reminder', '2-business-day reminder — the payment link hasn’t been used yet', 'To: Advisor'],
    ['ADVISOR_payment_confirmation|card', 'Onboarding payment by card — confirmation, no longer sent automatically (card gets the invoice/receipt instead)', 'To: Advisor'],
    ['ADVISOR_payment_confirmation|ach', 'Onboarding payment started by bank transfer (ACH) — confirmation', 'To: Advisor'],
    ['ADVISOR_invoice_receipt', 'Payment cleared — invoice and receipt PDFs attached', 'To: Advisor'],
    ['ADVISOR_login_setup', 'New member portal login — set-your-password link', 'To: Advisor'],
  ],
  'ACCOUNTANT_ONBOARDING': [
    ['ACCOUNTANT_undecided', 'Accountant is undecided after the intro meeting — decision email with Yes / No buttons', 'To: Accountant'],
    ['ACCOUNTANT_decline', 'Accountant is not proceeding — close-out (also sent on the 14-day auto-decline)', 'To: Accountant'],
    ['ACCOUNTANT_undecided_reminder', '2-business-day reminder — the decision email hasn’t been answered', 'To: Accountant'],
    ['ACCOUNTANT_agreement_sent', 'Accountant said yes — onboarding agreement signing link', 'To: Accountant'],
    ['ACCOUNTANT_signing_reminder', '2-business-day reminder — the agreement is still unsigned', 'To: Accountant'],
    ['ACCOUNTANT_ceo_countersign', 'Internal — asks Anton (CEO) to countersign once the accountant has signed', 'To: Anton (CEO)'],
    ['ACCOUNTANT_payment_link', 'Agreement fully signed — onboarding payment link', 'To: Accountant'],
    ['ACCOUNTANT_payment_reminder', '2-business-day reminder — the payment link hasn’t been used yet', 'To: Accountant'],
    ['ACCOUNTANT_payment_confirmation|card', 'Onboarding payment by card — confirmation, no longer sent automatically (card gets the invoice/receipt instead)', 'To: Accountant'],
    ['ACCOUNTANT_payment_confirmation|ach', 'Onboarding payment started by bank transfer (ACH) — confirmation', 'To: Accountant'],
    ['ACCOUNTANT_invoice_receipt', 'Payment cleared — invoice and receipt PDFs attached', 'To: Accountant'],
    ['ACCOUNTANT_login_setup', 'New member portal login — set-your-password link', 'To: Accountant'],
  ],
  'TEAM': [
    ['new_model_sale', 'Internal — announces a new advisor / accountant sale to the team', 'To: Team list (below)'],
  ],
  'SPECIALIST_ONBOARDING': [
    ['SPECIALIST_yes', 'Step 1 — invitation to continue after the preliminary meeting (agreement + revenue examples attached)', 'To: Specialist'],
    ['SPECIALIST_no', 'Step 1 — not proceeding after the preliminary meeting', 'To: Specialist'],
    ['SPECIALIST_sif_reminder', '2-business-day reminder — the Specialist Information Form hasn’t been submitted', 'To: Specialist'],
    ['SPECIALIST_step2_progress', 'Step 2 — progress update while the detail meetings continue', 'To: Specialist'],
    ['SPECIALIST_vote_reminder', 'Internal — 2-business-day reminder that an executive hasn’t voted yet', 'To: Executive'],
    ['SPECIALIST_denied', 'The executives declined the application', 'To: Specialist'],
    ['SPECIALIST_step3', 'Step 2 complete — moving into Step 3 (due diligence)', 'To: Specialist'],
    ['SPECIALIST_step3_proceed', 'Step 3 — cleared to proceed after their questions were resolved', 'To: Specialist'],
    ['SPECIALIST_choice_reminder', '2-business-day reminder — a background-check option hasn’t been chosen', 'To: Specialist'],
    ['SPECIALIST_bg_confirmation|card', 'Background-check payment by card — confirmation, no longer sent automatically (card gets the receipt instead)', 'To: Specialist'],
    ['SPECIALIST_bg_confirmation|ach', 'Background-check payment started by bank transfer (ACH) — confirmation', 'To: Specialist'],
    ['SPECIALIST_bg_receipt', 'Background-check payment cleared — invoice and receipt PDFs attached', 'To: Specialist'],
    ['SPECIALIST_bg_passed', 'Background check passed — moving on', 'To: Specialist'],
    ['SPECIALIST_ddc_reminder', '2-business-day reminder — the due-diligence checklist hasn’t been submitted', 'To: Specialist'],
    ['SPECIALIST_ddc_edits', 'The due-diligence checklist needs edits (includes the reason)', 'To: Specialist'],
    ['SPECIALIST_ddc_approved', 'Due-diligence checklist approved', 'To: Specialist'],
    ['SPECIALIST_revshare_complete', 'Revenue-share proposal is ready for their response', 'To: Specialist'],
    ['SPECIALIST_revfinal_reminder', '2-business-day reminder — the revenue-share proposal hasn’t been answered', 'To: Specialist'],
    ['SPECIALIST_agreement_sent', 'Step 4 — VFO Specialist Agreement signing link', 'To: Specialist'],
    ['SPECIALIST_signature_reminder', '2-business-day reminder — the agreement is still unsigned', 'To: Specialist'],
    ['SPECIALIST_ceo_countersign', 'Internal — asks Anton (CEO) to countersign once the specialist has signed', 'To: Anton (CEO)'],
    ['SPECIALIST_lic_payment', 'Step 4 — link to set up the $99/month VFO license subscription', 'To: Specialist'],
    ['SPECIALIST_licpayment_reminder', '2-business-day reminder — the license subscription hasn’t been set up', 'To: Specialist'],
    ['SPECIALIST_lic_confirmation|card', 'License payment by card — confirmation, no longer sent automatically (card gets the monthly invoice/receipt instead)', 'To: Specialist'],
    ['SPECIALIST_lic_confirmation|ach', 'License payment started by bank transfer (ACH) — confirmation', 'To: Specialist'],
    ['SPECIALIST_lic_invoicereceipt', 'Monthly license invoice and receipt PDFs (sent every month)', 'To: Specialist'],
    ['SPECIALIST_skool_invite', 'Going live — VFO Skool community invite', 'To: Specialist'],
    ['SPECIALIST_login_setup', 'Specialist portal login — set-your-password link', 'To: Specialist'],
  ],
  'SPECIALIST_LICENSE_CONTINUATION': [
    ['SPECIALIST_lic_continuation_request', 'Moves an existing specialist onto the portal’s $99/month license — set-up link', 'To: Specialist'],
  ],
  'CLIENT_PAYMENT_CONTINUATION': [
    ['setup_link', 'Migrated client — link to add their card or bank account so payments can continue', 'To: Client'],
    ['setup_link_reminder', 'Nudges a migrated client who was sent the payment-method setup link but never saved a card or bank', 'To: Client'],
  ],
  'MEMBER_MEMBERSHIP_FEES': [
    ['MEMBERSHIP_setup_link', 'Membership fee plan created — link where the member pays their first payment and saves their card or bank account', 'To: Member'],
    ['MEMBERSHIP_transfer_setup_link', 'Member moving over from the old billing mid-year — same setup link, but explains the transfer and where they are in their year', 'To: Member'],
    ['MEMBERSHIP_payment_failed', 'A monthly membership charge failed — asks the member to update their payment method and pay the arrears now at their /membership-pay link', 'To: Member'],
    ['MEMBERSHIP_arrears_digest', 'Friday-morning digest listing every member currently in arrears on membership fees (member number, name, amount, months) — sends "no one in arrears" when the list is empty', 'To: Paul'],
    ['MEMBERSHIP_update_link', 'Admin-sent fresh update-payment-method link for an active plan (links expire after 30 days)', 'To: Member'],
    ['MEMBERSHIP_confirmation|card', 'First sign-up on card — immediate acknowledgement that the payment went through; invoice and receipt follow moments later', 'To: Member · Cc: Tray · Bcc: Paul, Anna'],
    ['MEMBERSHIP_confirmation|ach', 'First sign-up on ACH — immediate acknowledgement; invoice and receipt follow when the transfer clears', 'To: Member · Cc: Tray · Bcc: Paul, Anna'],
    ['MEMBERSHIP_invoicereceipt_email|first', 'First payment of a brand-new membership — invoice and receipt attached', 'To: Member · Cc: Tray · Bcc: Paul, Anna'],
    ['MEMBERSHIP_invoicereceipt_email|renewal', 'Opening payment of a renewed membership year — new-year invoice and receipt attached', 'To: Member · Cc: Tray · Bcc: Paul, Anna'],
    ['MEMBERSHIP_invoicereceipt_email|transfer', 'First payment after moving over from the old billing — catch-up invoice showing where they are in the year, plus receipt', 'To: Member · Cc: Tray · Bcc: Paul, Anna'],
    ['MEMBERSHIP_receipt_email|monthly', 'Every later monthly pull — receipt only, no invoice', 'To: Member · Cc: Tray · Bcc: Paul, Anna'],
    ['MEMBERSHIP_renewal_notice', 'Thirty days before the membership renews — what renews and when, with a button to request a meeting about it', 'To: Member · Cc: Tray, Rachael · Bcc: Anton, Paul'],
    ['MEMBERSHIP_next_year_terms', "Sent when an admin saves next year's terms on an active plan — confirms the renewal date, the member type and the annual value, charged the same way on the same method", 'To: Member · Cc: Tray, Rachael · Bcc: Anton, Paul'],
    ['MEMBERSHIP_cancel_confirmation', 'The renewal meeting ended in a cancellation — confirms auto-renew is off and the current year completes as contracted', 'To: Member · Cc: Tray, Rachael · Bcc: Anton, Paul'],
  ],
  'PARTNERSHIP_FAST_TRACK': [
    ['PFT_meeting_confirm', 'A PFT meeting is booked — confirmation (used for every meeting in the track)', 'To: Accountant'],
    ['PFT_meeting_declined', 'Meeting declined — close-out', 'To: Accountant'],
    ['PFT_discovery_reminder', '2-business-day reminder — the discovery form hasn’t been submitted', 'To: Accountant'],
    ['PFT_decision_vfo_ft', 'Decision: VFO Fast Track — email with the two response buttons', 'To: Accountant'],
    ['PFT_decision_vfo_ft_reminder', '2-business-day reminder — the Fast Track response is still outstanding', 'To: Accountant'],
    ['PFT_decision_vfo_associate', 'Decision: VFO Associate — email with the two response buttons (confirm / request another meeting)', 'To: Accountant'],
    ['PFT_decision_no', 'Decision: No — close-out', 'To: Accountant'],
    ['PFT_decision_undecided', 'Decision: Undecided — email with the three path buttons (VFO FT / VFO Associate / No) for the client to self-select', 'To: Accountant'],
  ],
  'GROWTH_CREDITS': [
    ['GC_redemption_confirmation', 'Redemption confirmation — the member spent credits on a marketplace service', 'To the member, CC the allocated team member'],
  ],
  'PAYMENTS': [
    ['card_update', 'Secure link for someone to change their saved card or bank account', 'To: Chosen client / member / specialist'],
  ],
  'VFO_SPECIALIST_REVENUE': [
    ['SPECREV_payment_request', 'The revenue bill — asks the specialist to pay their revenue amount', 'To: Specialist'],
    ['SPECREV_payment_reminder', '2-business-day reminder — the revenue bill hasn’t been paid', 'To: Specialist'],
    ['SPECREV_payment_confirmation', 'The specialist paid by bank transfer (ACH) — confirmation while it clears (not sent for card, which gets the invoice/receipt)', 'To: Specialist'],
    ['SPECREV_invoice_receipt_email', 'Funds cleared — invoice and receipt PDFs attached', 'To: Specialist'],
    ['SPECREV_revenue_share_confirmation', 'A recipient’s share was transferred — confirmation', 'To: Recipient (member / specialist)'],
    ['SPECREV_money_mapping_notice', 'A recipient’s share was allocated to Money Mapping — notice, no transfer', 'To: Recipient (member / specialist)'],
    ['SPECREV_connect_setup', 'A recipient needs to set up their payment details (Stripe Connect) before they can be paid', 'To: Recipient (member / specialist)'],
    ['SPECREV_recurring_setup', 'The recurring setup link — asks the specialist to authorize an automatic monthly ACH payment', 'To: Specialist'],
    ['SPECREV_recurring_setup_confirmation', 'The specialist finished recurring ACH setup — confirms the monthly amount and charge day', 'To: Specialist'],
    ['SPECREV_recurring_setup_reminder', 'Nudges a specialist who was sent the recurring ACH setup link but never completed it', 'To: Specialist'],
  ],
  'MEMBER_PAYOUT': [
    ['member_connect_setup', 'Member payout setup — Stripe Connect onboarding link so they can receive revenue share', 'To: Member'],
  ],
  'SPECIALIST_PAYOUT': [
    ['specialist_connect_setup', 'Specialist payout setup — Stripe Connect onboarding link so they can receive revenue share'],
  ],
  'VAULT': [
    ['VAULT_request_documentation', 'Request documentation button (all vaults — client / member / specialist, Sensitive + General) — emails the person your documentation request with a secure upload link', 'To: Recipient · Cc: Member (client requests only)'],
  ],
  'STRATEGIC': [
    ['strategic_group_connect_setup', 'Strategic partner payout setup — Stripe Connect onboarding link for the partner company'],
    ['strategic_partner_revshare', 'Strategic partner revenue share — the 10% share confirmation sent to the partner company'],
  ],
  'MEMBERS': [
    ['MEMBER_revshare_held', 'Revenue share held — internal notice when a suspended/paused member\'s revenue share is parked instead of paid (any pipeline); it releases automatically on reinstatement', 'To: Paul · Cc: Anton, Tray, Tracy'],
    ['MEMBER_revshare_held_arrears', 'Revenue share held — internal notice when a member in arrears on membership fees has a revenue share parked instead of paid (any pipeline); it releases automatically once the arrears are paid', 'To: Paul · Cc: Anton, Tray, Tracy'],
  ],
}

// Role tokens the backend resolver understands (utils/email-recipients.ts).
// Stored in to_list/cc_list/bcc_list alongside raw emails; resolved to real
// addresses at send time per pipeline. Unknown-for-a-pipeline tokens are
// silently skipped by the backend, so they're safe anywhere.
export const ROLE_LABELS = {
  CLIENT: 'Client',
  MEMBER: 'Member',
  ASSIGNED_PF: 'Assigned PF',
  TAX_PLANNER: 'Tax Planner + allocated Team Member',
  SPECIALIST: 'Specialist',
  ADVISOR: 'Advisor',
  ACCOUNTANT: 'Accountant',
  TEAM_MEMBER: 'Team member responsible',
  TEAM: 'Team (all admins)',
  RECIPIENT: 'Default recipient',
}

// Bracket-token -> short plain-English label for the per-step email previews.
// Keys are the inner token text WITHOUT the surrounding brackets.
export const TOKEN_LEGEND = {
  'Client Name': "client's full name",
  'Client First': "client's first name",
  'Client Ref': "client reference number",
  'Member Name': "member's full name",
  'Member First': "member's first name",
  'MEMBER_NAME': "member's full name",
  'FULL_NAME': 'full name',
  'FIRST_NAME': 'first name',
  'SPECIALIST_NAME': "specialist's name",
  'Specialist Name': "specialist's name",
  'Recipient Name': "recipient's full name",
  'Recipient First': "recipient's first name",
  'Advisor Name': "advisor's name",
  'Accountant Name': "accountant's name",
  'Payment Amount': 'payment amount',
  'Amount': 'amount',
  'Failed Amount': 'amount that failed',
  'CARD_FEE_TEXT': 'card-fee note (if paying by card)',
  'PROCESSING_TIME': 'processing time',
  'PAYMENT_LABEL': 'payment label',
  'Payment Number': 'payment number',
  'Receipt Number': 'receipt number',
  'Invoice Number': 'invoice number',
  'Kind Label': 'kind label',
  'Subject Suffix': 'subject suffix',
  'Service Level': 'service level',
  'PRIORITIES': 'list of priorities',
  'NEXT_MEETING_TITLE': 'next meeting title',
  'CLOSING': 'closing line',
  'DECLINE_REASON': 'reason for declining',
  'REQUESTED_INFO': 'requested additional information',
  'UPLOAD_BUTTON': 'secure upload button',
  'AGREEMENT_NAME': 'agreement name',
  'SELECTED_PLANS': 'selected plans',
  'Month': 'month',
  'Year': 'year',
  'PAYMENT_SCHEDULE': 'payment schedule',
  'X': 'payment number',
  'Y': 'total payments',
}

// Friendly label for a bracket token's inner text: the legend entry, else a
// prettified fallback (underscores -> spaces, lower-cased, first letter capped).
export function friendlyToken(inner) {
  if (Object.prototype.hasOwnProperty.call(TOKEN_LEGEND, inner)) return TOKEN_LEGEND[inner]
  const cleaned = String(inner).replace(/_/g, ' ').trim().toLowerCase()
  if (!cleaned) return inner
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1)
}
